### ISSUE TITLE
Element type is invalid

### ISSUE THREAD

**Issue by abeikverdi** [niftylettuce/react-native-loading-spinner-overlay#17]
I get this error on RN v27:
Element type is invalid;: expected a string (for built-in components) or a class/function (for composite components) but got undefined: check the render method of Spinner.

And this is my spinner in render:
<Spinner visible={this.state.visible} />

**Comment by nfrolov** [comment]
There should be major/minor version bump, because 0.1.2 is broken on RN older than 0.28 . Had to force version 0.1.1.

**Comment by niftylettuce** [comment]
Sorry I thought I did do a major bump.  I will add deprecation notice, try to unpublish last version, and bump major version.

**Comment by niftylettuce** [comment]
I have requested to unpublish version 0.1.2 here https://github.com/npm/npm/issues/13297.

I have also added a deprecation notice to 0.1.2 that says:

> React Native <= v0.27.x will not work on version 0.1.2, please use version 0.1.1 for RN <= 27 or 0.2.x for RN >= 28 instead

I have also published version 0.2.x to NPM and here on GitHub.

**Comment by abeikverdi** [comment]
Perfect! nice job

**Comment by niftylettuce** [comment]
Sorry that I caused this guys 😦

**Comment by niftylettuce** [comment]
See https://github.com/niftylettuce/react-native-loading-spinner-overlay/issues/20#issuecomment-231388519
